# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  elm-build:
    cmds:
      - elm make elm/Main.elm --output=www/js/elm.js
    sources:
      - elm/*.elm

  android-run:
    deps:
      - elm-build
    cmds:
      - cordova run android

  android-build:
    deps:
      - elm-build
    cmds:
      - cordova build android
    sources:
      - platforms/android/platform_www/**/*
      - platforms/android/app/**/*.java

