# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  plugin-update:
    cmds:
      - cordova plugin rm cordova-plugin-mixnet
      - cordova plugin add ./mixnet-plugin
    sources:
      - mixnet-plugin/www/mixnet.js
      - mixnet-plugin/src/android/*.java

  elm-build:
    cmds:
      - elm make elm/Main.elm --output=www/js/elm.js
    sources:
      - elm/*.elm

  android-run:
    deps:
      - plugin-update
      - elm-build
    cmds:
      - cordova run android

  android-build:
    deps:
      - plugin-update
      - elm-build
    cmds:
      - cordova build android
    sources:
      - platforms/android/platform_www/**/*
      - platforms/android/app/**/*.java

